[package]
  authors.workspace = true
  edition.workspace = true
  name              = "server"
  version.workspace = true

[dependencies]
  anyhow.workspace             = true
  proto                        = {path = "../proto"}
  thiserror.workspace          = true
  tokio.workspace              = true
  tonic.workspace              = true
  tracing.workspace            = true
  tracing-subscriber.workspace = true
