[workspace]
  default-members = ["crates/hello-world"]
  members         = ["crates/hello-world"]
  resolver        = "2"

  [workspace.dependencies]
    anyhow         = "1.0"
    gpui           = "0.2.2"
    gpui-component = "0.3.1"
    hello-world    = {path = "crates/hello-world"}
