[config]
  default_to_workspace = false

[tasks.default]
  alias = "deploy-plugins"

[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[tasks.clippy]
  args    = ["clippy"]
  command = "cargo"

[tasks.check]
  args    = ["check"]
  command = "cargo"

[tasks.format]
  args          = ["fmt"]
  command       = "cargo"
  dependencies  = ["check", "clippy"]
  install_crate = "rustfmt"

[tasks.build]
  args         = ["build", "--profile", "dev"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.deploy-plugins]
  args         = ["./deploy-plugins.sh"]
  command      = "bash"
  dependencies = ["build"]
  workspace    = false

[tasks.release]
  args         = ["build", "--profile", "release"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.watch-run]
  # `cargo install cargo-watch`로 설치
  args          = ["watch", "-x", "run", "--bin", "cli"]
  command       = "cargo"
  dependencies  = ["deploy-plugins"]
  install_crate = "cargo-watch"
  workspace     = false

[tasks.run]
  args         = ["run", "--bin", "cli"]
  command      = "cargo"
  dependencies = ["deploy-plugins"]
  workspace    = false
