# [REQ-R001] Loco 웹 애플리케이션 메인 크레이트 (2026-02-07)
[package]
name = "demo-app"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "demo_app-cli"

[dependencies]
loco-rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
regex = { version = "1.11" }
migration = { workspace = true }
demo-core = { workspace = true }
sea-orm = { workspace = true }
chrono = { workspace = true }
validator = { workspace = true }
uuid = { workspace = true }
include_dir = { version = "0.7" }
# view engine i18n
fluent-templates = { version = "0.13", features = ["tera"] }
unic-langid = { version = "0.9" }
# /view engine
axum-extra = { version = "0.10", features = ["form"] }

[[bin]]
name = "demo_app-cli"
path = "src/bin/main.rs"
required-features = []

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = { version = "3.1.1" }
rstest = { version = "0.25" }
insta = { version = "1.34", features = ["redactions", "yaml", "filters"] }
