[package]
  authors.workspace = true
  edition.workspace = true
  name              = "benches"
  version.workspace = true

[dependencies]
  proto           = {path = "../proto"}
  server          = {path = "../server"}
  tokio.workspace = true
  tonic.workspace = true

[[bench]]
  harness = false
  name    = "product_service_bench"
