[package]
  authors.workspace = true
  edition.workspace = true
  name              = "greeting-common"
  version.workspace = true

[dependencies]
  thiserror.workspace = true
  tonic.workspace     = true
