[package]
  edition = "2024"
  name    = "cli"
  version = "0.1.0"

[dependencies]
  plugin-interface = {path = "../../crates/plugin-interface"}
  plugin-manager   = {path = "../../crates/plugin-manager"}
