[package]
  authors.workspace = true
  edition.workspace = true
  name              = "greeting-server"
  version.workspace = true

[[bin]]
  name = "server"
  path = "src/main.rs"

[dependencies]
  greeting-common = {path = "../common"}
  greeting-proto  = {path = "../proto"}
  tokio.workspace = true
  tonic.workspace = true
