[package]
name = "greeting-server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
greeting-proto = { path = "../proto" }
greeting-common = { path = "../common" }
tokio.workspace = true
tonic.workspace = true
