[package]
  authors.workspace = true
  edition.workspace = true
  name              = "greeting-client"
  version.workspace = true

[[bin]]
  name = "client"
  path = "src/main.rs"

[dependencies]
  greeting-common = {path = "../common"}
  greeting-proto  = {path = "../proto"}
  tokio.workspace = true
  tonic.workspace = true

[dev-dependencies]
  criterion.workspace = true
  greeting-server     = {path = "../server"}

[[bench]]
  harness = false
  name    = "client_benchmark"
